### ISSUE TITLE
Complete Axiomatic Tests - implement missing Graql query scenarios

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/verification#18]
The BDD scenarios currently cover relatively comprehensively (except verification/errors that should throw as in #11):
* Undefine
* Define
* insert
* match
* delete

Some missing tests that should be implemented have the scenario names written in the respective feature files: match, get, insert all have missing implementations.

I will supervise as needed when completing this task

**Comment by alexjpwalker** [comment]
The implementation of missing scenarios is complete
