### ISSUE TITLE
End-to-end resolution testing

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/verification#27]
## Objective

Broadly, the generation of a query from the explanations of an inferred answer is complete #24, and forward chaining to complete a KB is also working #23.

What remains is to interface the two, and iron out any issues that arise. This includes:

- [x] Enforce that all data have keys #25 
- [x] Generate random keys when forward chaining (because inserting data requires keys)
- [x] Add explicit variables to relations with anonymous variables when building the resolution query
- [x] Upgrade the framework to work for any pattern, not just conjunctive statements [https://github.com/graknlabs/verification/issues/26](https://github.com/graknlabs/verification/issues/26)
- [x] Investigate whether we do need unification
- [x] Use different variables for each application of a rule in the case that we don't unify
- [x] Write test for the full procedure
- [x] Enforce that all entity and relation _types_ have keys
- [x] Implement completeness check
- [x] De-duplication of inferred concepts during forward chaining
- [ ] Test server architecture
- [ ] ~~BDD integration with client-java~~ (only to be implemented in Grakn Core)
- [x] BDD integration with grakn-core

**Comment by alexjpwalker** [comment]
client-java needs to be fixed in order to run the graql reasoner tests: https://github.com/graknlabs/client-java/pull/106/commits/78613e777db61f2713f0607db3ce02e14e14077c

**Comment by jmsfltchr** [comment]
Solved by https://github.com/graknlabs/grakn/pull/5798
